[build-system]
requires = [
    "maturin>=1.8.6,<2",
    "cffi>=1.14; platform_python_implementation != 'PyPy'"
]
backend-path = ["."]
build-backend = "backend"


[project]
name = "snakegram"
version = "1.0.0.dev1"

authors = [
    { name = "Milad" }
]

license = "Apache-2.0"
license-files = ["LICENSE"]

readme = "README.md"
description = "Telegram client library for Python."

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Communications :: Chat",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Typing :: Typed"
]

dependencies = [
    "typing_extensions>=4.12"
]
requires-python = ">=3.8"

#
[tool.maturin]
locked = true
module-name = "snakegram._rust"
manifest-path = "extension/Cargo.toml"
python-packages = ["snakegram"]


[project.urls]
source = "https://github.com/mivmi/snakegram"
issues = "https://github.com/mivmi/snakegram/issues"


[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1"
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
