name: Rust

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "14.5"

jobs:
  build:
    strategy:
      matrix:
        python: [3.11]
        include:
          - os: ubuntu-latest
            arch: x86_64
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: armv7
            target: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            arch: aarch64
            target: aarch64-unknown-linux-gnu
          # - os: macos-latest
            # arch: x86_64
            # target: x86_64-apple-darwin
          # - os: windows-latest
            # arch: x86_64
            # target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: cargo build --release

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheel with maturin-action
        uses: PyO3/maturin-action@v1.43.0
        with:
          command: build
          args: --release --out dist
          manylinux: auto
          sccache: true 

      - name: Create ./root/extensions and copy wheels
        run: |
          mkdir -p ./root/extensions
          cp dist/*.whl ./root/extensions/ || (echo "No wheel files found in dist/" && exit 1)
          echo "Wheels copied:"
          ls -l ./root/extensions

      - name: Upload wheels as workflow artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pyo3-wheels-${{ matrix.python }}
          path: ./root/extensions/*.whl
